// ADVERT TYPES
export const FETCH_ADVERTS_REQUEST = 'FETCH_ADVERTS_REQUEST';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILURE';
export const FETCH_MEMBER_ADVERTS_REQUEST = 'FETCH_MEMBER_ADVERTS_REQUEST';
export const FETCH_MEMBER_ADVERTS_SUCCESS = 'FETCH_MEMBER_ADVERTS_SUCCESS';
export const FETCH_MEMBER_ADVERTS_FAILURE = 'FETCH_MEMBER_ADVERTS_FAILURE';

// TAGS TYPES
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

// USER TYPES
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SET_USER = 'SET_USER';

// PAGINATION TYPES
export const SET_PAGINATION_FILTERS = 'SET_PAGINATION_FILTERS';
