// ADVERT TYPES
export const FETCH_ADVERTS_REQUEST = 'FETCH_ADVERTS_REQUEST';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILURE';
export const FETCH_ADVERT_REQUEST = 'FETCH_ADVERT_REQUEST';
export const FETCH_ADVERT_SUCCESS = 'FETCH_ADVERT_SUCCESS';
export const FETCH_ADVERT_FAILURE = 'FETCH_ADVERT_FAILURE';
export const FETCH_MEMBER_ADVERTS_REQUEST = 'FETCH_MEMBER_ADVERTS_REQUEST';
export const FETCH_MEMBER_ADVERTS_SUCCESS = 'FETCH_MEMBER_ADVERTS_SUCCESS';
export const FETCH_MEMBER_ADVERTS_FAILURE = 'FETCH_MEMBER_ADVERTS_FAILURE';
export const SET_ADVERT_TO_DELETE = 'SET_ADVERT_TO_DELETE';
export const DELETE_ADVERT_REQUEST = 'DELETE_ADVERT_REQUEST';
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS';
export const DELETE_ADVERT_FAILURE = 'DELETE_ADVERT_FAILURE';
export const CREATE_ADVERT_REQUEST = 'CREATE_ADVERT_REQUEST';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const CREATE_ADVERT_FAILURE = 'CREATE_ADVERT_FAILURE';
export const EDIT_ADVERT_REQUEST = 'EDIT_ADVERT_REQUEST';
export const EDIT_ADVERT_SUCCESS = 'EDIT_ADVERT_SUCCESS';
export const EDIT_ADVERT_FAILURE = 'EDIT_ADVERT_FAILURE';


// TAGS TYPES
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

// USER TYPES
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const UNSUBSCRIBE_REQUEST = 'UNSUBSCRIBE_REQUEST';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_FAILURE = 'UNSUBSCRIBE_FAILURE';
export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILURE = 'UPDATE_USER_PASSWORD_FAILURE';
export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const SET_USER = 'SET_USER';

// PAGINATION TYPES
export const SET_PAGINATION_FILTERS = 'SET_PAGINATION_FILTERS';
